# Generated by Django 5.2.4 on 2025-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='department',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='fullname',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('onhold', 'On-hold'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='received', max_length=300, verbose_name='Status'),
        ),
    ]
